### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by fanspace** [michelloworld/ez-gin-template#5]
some pages like sign in / sign up ,  i donot want to include  top/left/foot etc.  how can i do?

**Comment by michelloworld** [comment]
I would recommend you to create a new layout for sign in and sign up pages.

And by default this package will not include partial template if you are not call `{{template "your_partial_template" .}}`

Please check this example (line 7): [https://github.com/michelloworld/ez-gin-template/blob/master/example/app/views/blogs/index.html](https://github.com/michelloworld/ez-gin-template/blob/master/example/app/views/blogs/index.html)
