### ISSUE TITLE
How to use example?

### ISSUE THREAD

**Issue by muety** [michelloworld/ez-gin-template#6]
How does the complete Go code for your example look like, i.e. how would you get the blog to render? Probably you would have to add something like:

```go
router.GET("/", func(c *gin.Context) {
		c.HTML(http.StatusOK, "blog/index", gin.H{
			"blogs": []Blog,
		})
	})
```

**Comment by michelloworld** [comment]
yes, like your example.

`c.HTML(http.StatusOK, "articles/list", "")`
